In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("test.csv")

In [2]:
def get_knn_edges(x, y, k):
    """ 
    Given x and y coordinates of nodes, compute edges for a k-NN graph.

    Args:
        x (numpy array): x-coordinates of nodes.
        y (numpy array): y-coordinates of nodes.
        k (int): Number of nearest neighbors.

    Returns:
        sources (numpy array): List of source nodes.
        destinations (numpy array): List of destination nodes.
    """
    n = len(x)

    # Compute pairwise distances
    x_diff = x[:, np.newaxis] - x[np.newaxis, :]
    y_diff = y[:, np.newaxis] - y[np.newaxis, :]
    distances = np.sqrt(x_diff**2 + y_diff**2)

    # Get the indices of the k nearest neighbors for each node (excluding self-connections)
    knn_indices = np.argsort(distances, axis=1)[:, 1:k+1]

    # Create source and destination lists
    sources = np.repeat(np.arange(n), k)
    destinations = knn_indices.flatten()

    return sources, destinations

In [6]:
x = df["cog_x"].values
y = df["cog_y"].values
x_diff = x[:, np.newaxis] - x[np.newaxis, :]
y_diff = y[:, np.newaxis] - y[np.newaxis, :]



In [18]:
x

array([-8.58187309e+01,  7.02230800e+01, -5.68355437e+01,  7.24089550e+01,
        2.65573817e+00,  3.78364394e+01, -7.08096574e+01, -7.27117507e+01,
        5.04267427e+01, -7.26570653e+01, -7.58302070e+01,  6.24189235e+01,
       -9.56646895e+00, -8.38682669e+01, -3.04900489e+00,  1.15912797e+01,
        1.30738802e+01,  8.53280631e+00, -3.28605771e+01,  2.68112586e+01,
        6.52904090e+01, -4.49160887e+00,  1.89974009e+00,  1.56160417e+01,
        1.03343153e+02, -7.33643319e+00, -1.14885639e+02, -2.44773732e+01,
        4.36918448e+01,  7.47863894e+00,  2.70725361e+01, -6.87568879e+00,
       -2.85716725e+01,  3.69891453e+01, -3.00487059e+01, -2.06829516e+01,
        5.67769958e+01,  2.34611572e+01, -1.89208490e+01, -6.51843586e+01,
        4.09961451e+01, -1.27488273e+01,  5.29106431e+01,  4.30794532e-01,
        3.68519679e+01,  1.46292565e+01, -9.23545512e+00,  2.15982122e+01,
       -8.26865012e-02,  2.72256206e+00])

In [19]:
x[np.newaxis,:]

array([[-8.58187309e+01,  7.02230800e+01, -5.68355437e+01,
         7.24089550e+01,  2.65573817e+00,  3.78364394e+01,
        -7.08096574e+01, -7.27117507e+01,  5.04267427e+01,
        -7.26570653e+01, -7.58302070e+01,  6.24189235e+01,
        -9.56646895e+00, -8.38682669e+01, -3.04900489e+00,
         1.15912797e+01,  1.30738802e+01,  8.53280631e+00,
        -3.28605771e+01,  2.68112586e+01,  6.52904090e+01,
        -4.49160887e+00,  1.89974009e+00,  1.56160417e+01,
         1.03343153e+02, -7.33643319e+00, -1.14885639e+02,
        -2.44773732e+01,  4.36918448e+01,  7.47863894e+00,
         2.70725361e+01, -6.87568879e+00, -2.85716725e+01,
         3.69891453e+01, -3.00487059e+01, -2.06829516e+01,
         5.67769958e+01,  2.34611572e+01, -1.89208490e+01,
        -6.51843586e+01,  4.09961451e+01, -1.27488273e+01,
         5.29106431e+01,  4.30794532e-01,  3.68519679e+01,
         1.46292565e+01, -9.23545512e+00,  2.15982122e+01,
        -8.26865012e-02,  2.72256206e+00]])

In [20]:

distances = np.sqrt(x_diff**2 + y_diff**2)

In [23]:
k = 5
knn_indices = np.argsort(distances, axis=1)[:, 1:k+1]

In [35]:
knn_indices.flatten()

array([ 6,  9, 39, 13, 10, 24, 42, 19, 20,  4, 27, 43, 18, 13, 29, 36, 40,
        5,  8, 33, 14, 46, 41, 19, 21, 40, 36, 33, 45, 28,  9, 39,  0, 13,
       10, 10,  0, 26, 32,  6, 44, 33, 11, 40, 37,  6, 39, 13,  0, 18,  7,
        0, 26,  6, 39, 20,  8, 44, 42, 33, 25, 41,  4, 46, 14,  9,  6, 39,
        0, 18, 46,  4, 21, 41, 32, 22, 17, 37, 29, 49, 23, 47, 48, 49, 17,
       49, 23, 15, 22, 48, 27, 38, 31, 35, 34,  4, 30, 14, 42, 46, 11, 42,
        8, 44, 30, 14, 46, 35, 38, 34, 15, 17, 49, 29, 31, 16, 17, 49, 37,
       48,  1, 20, 42, 11, 19, 12, 41,  4, 46, 14,  0, 10,  7,  6,  9, 18,
       31, 22, 38, 49,  5, 36, 40, 45,  3, 45, 15, 22, 43, 17, 47, 16, 44,
       23, 42, 48, 49, 17, 22, 38, 34, 46, 41, 14, 35, 40, 37, 44,  8,  5,
       35, 32, 38, 21, 46, 38, 34, 21, 32, 18,  3, 40,  5, 33,  8, 15, 23,
       33, 17, 44, 35, 18, 31, 34, 48,  6,  9, 13,  0, 18,  5, 33, 36, 37,
        8,  4, 46, 14, 32, 25, 20, 11, 30, 19, 47, 45, 29, 22, 15,  5,  8,
       37, 33, 23, 47, 29

In [29]:
n = len(x)

In [30]:
sources = np.repeat(np.arange(n), k)
destinations = knn_indices.flatten()


In [31]:
sources

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13,
       13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16,
       17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20,
       20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23,
       23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27,
       27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 30, 30, 30,
       30, 30, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33,
       34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 37, 37,
       37, 37, 37, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 40, 40, 40, 40,
       40, 41, 41, 41, 41, 41, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 44,
       44, 44, 44, 44, 45

In [36]:
a = np.arange(n)

In [37]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
np.tile(a,2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])