In [48]:
import uproot
import numpy as np
import pandas as pd

In [2]:
file_dir = "/hpc/group/vossenlab/rck32/eic/work_eic/root_files/Slurm/May_21/Run_0/"
num_files = 1
file_names = ["mu_5GeV_30events_run_0_file_1.edm4hep.root"]

In [5]:
tree_events = []
for i in range(num_files):
    tree_events.append(uproot.open(file_dir + file_names[i]+ ":events"))    

In [14]:
xpos = tree_events[0]['HcalBarrelHits/HcalBarrelHits.position.x'].array(library='np')

In [64]:
class HitsData:
    def __init__(self):
        self.layer_map = [1830.8000, 1841.4000, 1907.5, 1918.1,1984.1999, 1994.8000, 2060.8999,2071.5,2137.6001,2148.1999,2214.3000,2224.8999,2291,2301.6001,2367.6999,2378.3000,2444.3999,2455,2521.1001,2531.6999,2597.8000,2608.3999,2674.5,2685.1001,2751.1999,2761.8000,2827.8999,2838.5]
        self.labels = []
        self.data = pd.DataFrame({})
        self.addColumns()
    def addColumns(self):
        for i in range(28):
            name = f"layer{i}count"
            self.data[name] = []
    def createData(self,tree):
        for file in range(len(tree)):
            PDG = tree[file]['MCParticles/MCParticles.PDG'].array(library='np')
            for event in range(len(PDG)):
                self.labels.append(PDG_dict[PDG[event][0]]) #get PDG of first particle
                self.
    def processHits(self,tree):
        


In [66]:
myData = HitsData()
myData.createData(tree_events)
myData.layer_map[2]

1907.5

In [37]:
PDG = tree_events[0]['MCParticles/MCParticles.PDG'].array(library='np')
PDG[0][0]

13

In [31]:
#use PDG_dict to create labels
PDG_dict = {
    13 : 0,
    -211 : 1
}


for event in range(len(xpos)):
    label[]

In [33]:
PDG_dict[-211]

1

In [ ]:
import os
import pandas as pd
from torchvision.io import read_image

class CustomImageDataset(Dataset):
    def __init__(self, annotations_file, img_dir, transform=None, target_transform=None):
        self.img_labels = pd.read_csv(annotations_file)
        self.img_dir = img_dir
        self.transform = transform
        self.target_transform = target_transform

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_labels.iloc[idx, 0])
        image = read_image(img_path)
        label = self.img_labels.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label

In [26]:
tree_events[0]['MCParticles/MCParticles.PDG'].array(library='np')

array([array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([13, 11, 11, ..., 11, 11, 11], dtype=int32),
       array([